//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn.Clients
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageParameter", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Learn.Clients.GoodsQueryDto))]
    public partial class PageParameter : object
    {
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        private System.Collections.Generic.List<Learn.Clients.Ordering> OrderingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Collections.Generic.List<Learn.Clients.Ordering> Orderings
        {
            get
            {
                return this.OrderingsField;
            }
            set
            {
                this.OrderingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsQueryDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    public partial class GoodsQueryDto : Learn.Clients.PageParameter
    {
        
        private System.Nullable<double> PriceMinField;
        
        private System.Nullable<double> PriceMaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceMin
        {
            get
            {
                return this.PriceMinField;
            }
            set
            {
                this.PriceMinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<double> PriceMax
        {
            get
            {
                return this.PriceMaxField;
            }
            set
            {
                this.PriceMaxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordering", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    public partial class Ordering : object
    {
        
        private string NameField;
        
        private Learn.Clients.OrderingDirection DirectionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Learn.Clients.OrderingDirection Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderingDirection", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    public enum OrderingDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desc = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfGoodsDtoPd4vD4jW", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    public partial class PagedResultOfGoodsDtoPd4vD4jW : object
    {
        
        private System.Collections.Generic.List<Learn.Clients.GoodsDto> ResultField;
        
        private int ToltalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Learn.Clients.GoodsDto> Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToltalCount
        {
            get
            {
                return this.ToltalCountField;
            }
            set
            {
                this.ToltalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    public partial class GoodsDto : Learn.Clients.GoodsInDto
    {
        
        private System.DateTimeOffset CreateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsInDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Learn.Clients.GoodsDto))]
    public partial class GoodsInDto : object
    {
        
        private System.Nullable<System.Guid> IdField;
        
        private string NameField;
        
        private string PricingField;
        
        private System.Nullable<int> WordsField;
        
        private System.Nullable<double> DaysField;
        
        private double InitPriceField;
        
        private double PriceField;
        
        private string CurrencyField;
        
        private string CurrencySymbolField;
        
        private string DescriptionField;
        
        private System.DateTimeOffset StartTimeField;
        
        private System.DateTimeOffset EndTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pricing
        {
            get
            {
                return this.PricingField;
            }
            set
            {
                this.PricingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Words
        {
            get
            {
                return this.WordsField;
            }
            set
            {
                this.WordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<double> Days
        {
            get
            {
                return this.DaysField;
            }
            set
            {
                this.DaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double InitPrice
        {
            get
            {
                return this.InitPriceField;
            }
            set
            {
                this.InitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CurrencySymbol
        {
            get
            {
                return this.CurrencySymbolField;
            }
            set
            {
                this.CurrencySymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTimeOffset StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.DateTimeOffset EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jmlearn.com/", ConfigurationName="Learn.Clients.IGoodsOutService")]
    public interface IGoodsOutService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoods", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsResponse")]
        System.Threading.Tasks.Task<Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW> GetGoodsAsync(Learn.Clients.GoodsQueryDto queryDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoodsById", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsByIdResponse")]
        System.Threading.Tasks.Task<Learn.Clients.GoodsDto> GetGoodsByIdAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface IGoodsOutServiceChannel : Learn.Clients.IGoodsOutService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class GoodsOutServiceClient : System.ServiceModel.ClientBase<Learn.Clients.IGoodsOutService>, Learn.Clients.IGoodsOutService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GoodsOutServiceClient() : 
                base(GoodsOutServiceClient.GetDefaultBinding(), GoodsOutServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GoodsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GoodsOutServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GoodsOutServiceClient.GetBindingForEndpoint(endpointConfiguration), GoodsOutServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GoodsOutServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GoodsOutServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GoodsOutServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GoodsOutServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GoodsOutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW> GetGoodsAsync(Learn.Clients.GoodsQueryDto queryDto)
        {
            return base.Channel.GetGoodsAsync(queryDto);
        }
        
        public System.Threading.Tasks.Task<Learn.Clients.GoodsDto> GetGoodsByIdAsync(System.Guid id)
        {
            return base.Channel.GetGoodsByIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GoodsService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GoodsService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://127.0.0.1:43210/Goods/GoodsService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GoodsOutServiceClient.GetBindingForEndpoint(EndpointConfiguration.GoodsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GoodsOutServiceClient.GetEndpointAddress(EndpointConfiguration.GoodsService);
        }
        
        public enum EndpointConfiguration
        {
            
            GoodsService,
        }
    }
}
