//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientNet.Learn.Clients {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageParameter", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfClientNet.Learn.Clients.GoodsQueryDto))]
    public partial class PageParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WcfClientNet.Learn.Clients.Ordering> OrderingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Collections.Generic.List<WcfClientNet.Learn.Clients.Ordering> Orderings {
            get {
                return this.OrderingsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderingsField, value) != true)) {
                    this.OrderingsField = value;
                    this.RaisePropertyChanged("Orderings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsQueryDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    [System.SerializableAttribute()]
    public partial class GoodsQueryDto : WcfClientNet.Learn.Clients.PageParameter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceMaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceMin {
            get {
                return this.PriceMinField;
            }
            set {
                if ((this.PriceMinField.Equals(value) != true)) {
                    this.PriceMinField = value;
                    this.RaisePropertyChanged("PriceMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<double> PriceMax {
            get {
                return this.PriceMaxField;
            }
            set {
                if ((this.PriceMaxField.Equals(value) != true)) {
                    this.PriceMaxField = value;
                    this.RaisePropertyChanged("PriceMax");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordering", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    [System.SerializableAttribute()]
    public partial class Ordering : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClientNet.Learn.Clients.OrderingDirection DirectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WcfClientNet.Learn.Clients.OrderingDirection Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderingDirection", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    public enum OrderingDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desc = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfGoodsDtoPd4vD4jW", Namespace="http://schemas.datacontract.org/2004/07/System.Linq")]
    [System.SerializableAttribute()]
    public partial class PagedResultOfGoodsDtoPd4vD4jW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WcfClientNet.Learn.Clients.GoodsDto> ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToltalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WcfClientNet.Learn.Clients.GoodsDto> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToltalCount {
            get {
                return this.ToltalCountField;
            }
            set {
                if ((this.ToltalCountField.Equals(value) != true)) {
                    this.ToltalCountField = value;
                    this.RaisePropertyChanged("ToltalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    [System.SerializableAttribute()]
    public partial class GoodsDto : WcfClientNet.Learn.Clients.GoodsInDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset CreateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsInDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfClientNet.Learn.Clients.GoodsDto))]
    public partial class GoodsInDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PricingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencySymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset EndTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pricing {
            get {
                return this.PricingField;
            }
            set {
                if ((object.ReferenceEquals(this.PricingField, value) != true)) {
                    this.PricingField = value;
                    this.RaisePropertyChanged("Pricing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Words {
            get {
                return this.WordsField;
            }
            set {
                if ((this.WordsField.Equals(value) != true)) {
                    this.WordsField = value;
                    this.RaisePropertyChanged("Words");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<double> Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double InitPrice {
            get {
                return this.InitPriceField;
            }
            set {
                if ((this.InitPriceField.Equals(value) != true)) {
                    this.InitPriceField = value;
                    this.RaisePropertyChanged("InitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CurrencySymbol {
            get {
                return this.CurrencySymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencySymbolField, value) != true)) {
                    this.CurrencySymbolField = value;
                    this.RaisePropertyChanged("CurrencySymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTimeOffset StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.DateTimeOffset EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jmlearn.com/", ConfigurationName="Learn.Clients.IGoodsOutService")]
    public interface IGoodsOutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoods", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsResponse")]
        WcfClientNet.Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW GetGoods(WcfClientNet.Learn.Clients.GoodsQueryDto queryDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoods", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsResponse")]
        System.Threading.Tasks.Task<WcfClientNet.Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW> GetGoodsAsync(WcfClientNet.Learn.Clients.GoodsQueryDto queryDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoodsById", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsByIdResponse")]
        WcfClientNet.Learn.Clients.GoodsDto GetGoodsById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jmlearn.com/IGoodsOutService/GetGoodsById", ReplyAction="http://www.jmlearn.com/IGoodsOutService/GetGoodsByIdResponse")]
        System.Threading.Tasks.Task<WcfClientNet.Learn.Clients.GoodsDto> GetGoodsByIdAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGoodsOutServiceChannel : WcfClientNet.Learn.Clients.IGoodsOutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoodsOutServiceClient : System.ServiceModel.ClientBase<WcfClientNet.Learn.Clients.IGoodsOutService>, WcfClientNet.Learn.Clients.IGoodsOutService {
        
        public GoodsOutServiceClient() {
        }
        
        public GoodsOutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoodsOutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodsOutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodsOutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfClientNet.Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW GetGoods(WcfClientNet.Learn.Clients.GoodsQueryDto queryDto) {
            return base.Channel.GetGoods(queryDto);
        }
        
        public System.Threading.Tasks.Task<WcfClientNet.Learn.Clients.PagedResultOfGoodsDtoPd4vD4jW> GetGoodsAsync(WcfClientNet.Learn.Clients.GoodsQueryDto queryDto) {
            return base.Channel.GetGoodsAsync(queryDto);
        }
        
        public WcfClientNet.Learn.Clients.GoodsDto GetGoodsById(System.Guid id) {
            return base.Channel.GetGoodsById(id);
        }
        
        public System.Threading.Tasks.Task<WcfClientNet.Learn.Clients.GoodsDto> GetGoodsByIdAsync(System.Guid id) {
            return base.Channel.GetGoodsByIdAsync(id);
        }
    }
}
